#!/usr/bin/env bash
# Process and PID file

mkdir /var/run/myscript.pid
echo $$
trap 'echo "I hate the kill command"
	rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true
do
	echo "To infinity and beyond"
done
