#!/usr/bin/env bash
# displays To infinity and beyond indefinitely and I am invincibl!!! when receiving SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done

